# Generated by Django 3.1.7 on 2021-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_content_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(max_length=128, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='content',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Заголовок'),
        ),
    ]
