# Generated by Django 3.1.7 on 2021-03-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210306_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=32, verbose_name='Подзаголовок')),
                ('description', models.TextField(max_length=132, verbose_name='Описание')),
                ('video', models.FileField(upload_to='videos', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_image', verbose_name='')),
                ('about_us_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.aboutus', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Фото о нас',
                'verbose_name_plural': 'Фото о нас',
            },
        ),
        migrations.AlterField(
            model_name='content',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.logo', verbose_name='Логотип'),
        ),
    ]
